/**
 * `init-config` — creates a first-run `.env` scaffold with safe defaults. It never
 * overwrites an existing file without `--force`, prefers copying `.env.example`
 * (preserving comments), never inserts a real token, and marks the values the
 * operator must fill in. `.env` is git-ignored by the repository's `.gitignore`.
 */
import { existsSync, readFileSync, writeFileSync } from "node:fs";
import { EXIT } from "../exitCodes.js";
import { printJson, printLine, type Args } from "../output.js";

/** A minimal safe template used when `.env.example` is unavailable. */
const FALLBACK_TEMPLATE = `# Discord MCP Server configuration — fill in DISCORD_TOKEN before use.
DISCORD_TOKEN=your_bot_token_here
# Read-only mode is enabled by default (safe).
DISCORD_READ_ONLY=true
# Analytics is disabled by default.
DISCORD_ANALYTICS_ENABLED=false
# Content output through MCP is disabled by default (privacy).
DISCORD_ANALYTICS_ALLOW_CONTENT_OUTPUT=false
# Bot DMs collection is disabled by default.
DISCORD_ANALYTICS_COLLECT_BOT_DMS=false
`;

/** Ensures the safe defaults are present/forced in the scaffold content. */
function withSafeDefaults(content: string): string {
  const enforce: Record<string, string> = {
    DISCORD_READ_ONLY: "true",
    DISCORD_ANALYTICS_ENABLED: "false",
    DISCORD_ANALYTICS_ALLOW_CONTENT_OUTPUT: "false",
    DISCORD_ANALYTICS_COLLECT_BOT_DMS: "false",
  };
  let out = content;
  for (const [key, value] of Object.entries(enforce)) {
    const re = new RegExp(`^(${key})=.*$`, "m");
    if (re.test(out)) out = out.replace(re, `$1=${value}`);
    else out += `\n${key}=${value}\n`;
  }
  // Never carry a real token through; keep the placeholder.
  out = out.replace(/^(DISCORD_TOKEN)=.*/m, "$1=your_bot_token_here");
  const header =
    "# Generated by `init-config`. FILL IN: DISCORD_TOKEN (required). This file is git-ignored.\n";
  return out.startsWith("#") ? `${header}${out}` : `${header}${out}`;
}

export async function run(args: Args): Promise<number> {
  const path = args.get("path") ?? ".env";
  const force = args.bool("force");
  const dryRun = args.bool("dry-run");
  const json = args.bool("json");

  const exists = existsSync(path);
  if (exists && !force) {
    const msg = `${path} already exists; refusing to overwrite (use --force to replace).`;
    if (json) printJson({ ok: false, path, written: false, reason: "exists" });
    else printLine(msg);
    return EXIT.CONFIG;
  }

  const source = existsSync(".env.example")
    ? readFileSync(".env.example", "utf8")
    : FALLBACK_TEMPLATE;
  const content = withSafeDefaults(source);

  if (dryRun) {
    if (json)
      printJson({
        ok: true,
        path,
        written: false,
        dryRun: true,
        source: existsSync(".env.example") ? ".env.example" : "fallback",
      });
    else
      printLine(
        `[dry-run] would write ${path} (from ${existsSync(".env.example") ? ".env.example" : "built-in template"}); no file written.`,
      );
    return EXIT.SUCCESS;
  }

  writeFileSync(path, content);
  if (json) printJson({ ok: true, path, written: true, overwritten: exists });
  else
    printLine(
      `Wrote ${path}${exists ? " (overwritten)" : ""}. Fill in DISCORD_TOKEN before starting.`,
    );
  return EXIT.SUCCESS;
}
